---
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
env:
  - DATABASE_HOST=localhost DATABASE_USER=travis
before_install:
  - for i in {1..60}; do mysqladmin -u travis ping && break; sleep 1; done
script:
  - bundle exec rake
gemfile:
  - gemfiles/ar42.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
services:
  - mysql
jobs:
  exclude:
    - rvm: 2.7.1
      gemfile: gemfiles/ar42.gemfile
