---
dist: xenial
sudo: required
language: ruby
cache: bundler
rvm:
  - 2.3.6
  - 2.4.4
  - 2.5.1
before_install:
  - docker-compose up -d
  - function mysql_ping { mysqladmin -u root -h 127.0.0.1 -P 6033 ping > /dev/null 2> /dev/null; }
  - for i in {1..60}; do mysql_ping && break; sleep 1; done
script:
  - bundle exec rake
gemfile:
  - gemfiles/ar42.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
addons:
  apt:
    packages:
      - mysql-client-core-5.7
      - mysql-client-5.7
