services:
  client:
    build: .
    volumes:
      - ./:/mnt:ro
    depends_on:
      - mysql
    profiles:
      - extra
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
