version: "3.8"
services:
  client:
    build: .
    environment:
      MYSQL_PING_ATTEMPTS: "10"
      DATABASE_URL: mysql2://root@db/sakila
    volumes:
      - ./:/mnt
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
